### PR TITLE
fix(PopoverV2): move to up container parent ref definition

### PR DESCRIPTION
**Pull request by AregSoft**

### CODE REVIEW

**Review by hamikhambardzumyan — DISMISSED** [review]
Looks good to me

**Review by GaroGabrielyan — APPROVED** [review]

**Comment by NairaMisakyan** [comment]
If the `withoutPicker` prop is set to false, the calendar icon's mouse cursor should be the default arrow type. If the value is true, then the mouse cursor should be a hand. (In addition, the condition also applies when the disabled prop is set to false.)

**Review by NairaMisakyan — CHANGES_REQUESTED** [review]
If the withoutPicker prop is set to false, the calendar icon's mouse cursor should be the default arrow type. If the value is true, then the mouse cursor should be a hand. (In addition, the condition also applies when the disabled prop is set to false.)

**Review by NairaMisakyan — DISMISSED** [review]

**Review by NairaMisakyan — DISMISSED** [review]

**Review by NairaMisakyan — DISMISSED** [review]

**Review by hamikhambardzumyan — APPROVED** [review]
Looks good to me!

**Review by NairaMisakyan — APPROVED** [review]

**Pull request merged**
